### ISSUE TITLE
Generate stub server from OpenAPI document

### ISSUE THREAD

**Issue by blake-regalia** [Open-MBEE/flexo-mms-sysmlv2#1]
Using the [OpenAPI document](https://github.com/Systems-Modeling/SysML-v2-API-Services/blob/master/public/docs/openapi.json) for SysML-v2, generate a stub server for the Flexo microservice.

**Comment by blake-regalia** [comment]
done. https://github.com/Open-MBEE/flexo-mms-sysmlv2

**Comment by dlamoris** [comment]
think there's a 'groupId' and 'packageName' config to the generator we'll want to regenerate with (ex. org.openmbee.flexo.mms.sysmlv2), since the default is currently org.openapitools.server
or just refactor the packages in ide if regenerating requires too much fixing

**Comment by dlamoris** [comment]
Additional issues with the generated code:
The use of Resources to define routes is preventing route matching correctly. See
https://youtrack.jetbrains.com/issue/KTOR-6855/Use-Content-Negotiation-and-type-safe-routing-together
We may need to manually rewrite all the api routes to not use that feature (or at least the ones that use post and put with json bodies)

Json serialization/deserialization requires the `@Serializable` annotation on the data classes - this needs a custom serializer for properties of type java classes ex. java.util.UUID and java.net.URI, which is addressed in #3 

The generated data classes have issues with `@` character in property names, they need more work for json serialization/deserialization to work - should look into changing to kotlinx's json serialization instead of gson as all the model classes need changes (this is done in #3 for model classes and project api class examples, gson has issues with java.time.* classes in modern jdk that needs custom adapters https://github.com/google/gson/issues/1996)
